[package]
name = "enum_pipeline"
version = "0.1.0"
edition = "2018"
description = "Provides a way to use enums to describe and execute ordered data pipelines. ğŸ¦€ğŸ¾"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enum_pipeline_derive = {version = "0.1.0", path = "enum_pipeline_derive"}

[workspace]
members = ["enum_pipeline_derive"]
